uint32 min_x # min x coordinate of the workspace w.r.t camera frame
uint32 max_x # max x coordinate of the workspace w.r.t camera frame
uint32 min_y # min y coordinate of the workspace w.r.t camera frame
uint32 max_y # max y coordinate of the workspace w.r.t camera frame
float32 distance # average distance of the workspace w.r.t camera frame
uint32[] indices # the member indices w.r.t camera frame
